POPUP_DURATION = 8
POPUP_AUTO_PLAY = True
POPUP_THEME = 'default'
POPUP_WIDTH = 400
POPUP_POSITION = (1, 1)
POPUP_TRANSPARENCY = 230
POPUP_TITLE_LENGTH = 400
POPUP_BODY_LENGTH = 400

DEFAULT_POLLING_INTERVAL = 60 * 15
USER_IDLE_TIMEOUT = 60
POLL_WHEN_IDLE = False
ITEM_CACHE_AGE = 60 * 60 * 24 * 7
FEED_CACHE_SIZE = 1000
